---
- name: Install WireGuard OS CHeck
  hosts: wg_vpn
  become: false

  tasks:
    - name: Base information
      ansible.builtin.debug:
        msg:
          - "Distro_Name: '{{ ansible_distribution }}'"
          - "Distro_Version: '{{ ansible_distribution_version }}'"
          - "Distro_Release: '{{ ansible_distribution_release }}'"
          - "Distro_Family: '{{ ansible_os_family }}'"

    - name: Check if OS is supported
      ansible.builtin.fail:
        msg: "I'm sorry your OS or Version has not been tested yet"
      when: >
        ansible_distribution not in ["Debian", "Ubuntu", "Fedora", "CentOS", "AlmaLinux"] or
        ansible_distribution_version not in ["12", "22.04", "38", "9", "9.2"]

    - name: Check if OS Arch is supported
      ansible.builtin.fail:
        msg: "Im sorry, currently {{ ansible_architecture }} architecture is not supported yet"
      when: >
        ansible_architecture not in ['x86_64']

    - name: Confirm Unsupported OS
      pause:
        prompt: "{{ ansible_distribution }} is not officially supported by PiHole, continue? (yes/no)"
      register: confirm_ok_distro
      when: >
        ansible_distribution in ["AlmaLinux"]

    - name: Exit
      ansible.builtin.fail:
        msg: "Ok exiting..."
      when: >
        ansible_distribution in ["AlmaLinux"] and
        "confirm_ok_distro.user_input | bool == false"

    - name: Confirm SELinux
      pause:
        prompt: "This VM has SELinux enabled, which is not officially supported by PiHole, continue? (yes/no)"
      register: confirm_ok_selinux
      when: ansible_selinux.status == "enabled"

    - name: Exit
      ansible.builtin.fail:
        msg: "Ok exiting..."
      when: >
        "confirm_ok_selinux.user_input | bool == false" and
        ansible_selinux.status == "enabled"
