---
- name: Install dnscrypt-proxy for DoH support
  hosts: wg_vpn
  vars_files:
    - "../../vars/vars.yml"
  become: true

  tasks:
    - name: Install "dnscrypt-proxy" package for Debian/Ubuntu
      ansible.builtin.apt:
        name: dnscrypt-proxy
        update_cache: true
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install "dnscrypt-proxy" package RedHat/Alma/Amazon
      ansible.builtin.dnf:
        name: dnscrypt-proxy
        update_cache: true
        state: latest
      when: ansible_distribution in ["Fedora", "CentOS", "AlmaLinux"]

    - name: Set interface in dnscrypt-proxy
      ansible.builtin.lineinfile:
        path: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
        regexp: '^listen_addresses = .*'
        line: "listen_addresses = ['127.0.0.1:5053']"

    - name: Set server-names
      ansible.builtin.lineinfile:
        path: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
        regexp: '^server_names = .*'
        line: "server_names = ['cloudflare-security']"

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable dnscrypt-proxy
      ansible.builtin.systemd:
        name: dnscrypt-proxy.service
        enabled: true
        masked: no
        state: restarted
