---
- name: Enable and start services
  hosts: wg_vpn
  vars_files:
    - "../../vars/vars.yml"
  become: true

  tasks:
    - name: Enable wireguard ui daemon
      ansible.builtin.systemd:
        name: wireguard-ui-daemon.service
        enabled: true
        masked: no
        state: restarted

    - name: Enable wireguard ui path
      ansible.builtin.systemd:
        name: wgui.path
        enabled: true
        masked: no
        state: restarted

    - name: Enable wireguard ui path
      ansible.builtin.systemd:
        name: wgui.service
        enabled: true
        masked: no
        state: restarted

    - name: Enable pihole-FTL on Fedora/CentOS
      ansible.builtin.systemd:
        name: pihole-FTL
        enabled: true
        masked: no
        state: restarted
      when: ansible_distribution in ["Fedora", "CentOS", "AlmaLinux"]

    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - debug:
        msg:
          - "WireGuard GUI https://{{ ansible_host }}:8443/"
          - "PiHole Admin http://{{ ansible_default_ipv4.address }}/admin/"
          - "Happy Surfing"
