---
- name: Create self signed cert
  hosts: wg_vpn
  vars_files:
    - "../../vars/vars.yml"
  become: true

  tasks:
    - name: Install "python3-cryptography" package on Debian/Ubuntu
      ansible.builtin.apt:
        name: python3-cryptography
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install "python3-cryptography" package on Fedora/CentOS
      ansible.builtin.dnf:
        name: python3-cryptography
        state: latest
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: Create private key (RSA, 4096 bits) for Debian/Ubuntu
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/{{ SERVER_FQDN }}.key
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Create private key (RSA, 4096 bits) for Fedora/CentOS
      community.crypto.openssl_privatekey:
        path: /etc/ssl/{{ SERVER_FQDN }}.key
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: Create certificate signing request (CSR) for self-signed certificate for Debian/Ubuntu
      community.crypto.openssl_csr:
        path: /etc/ssl/{{ SERVER_FQDN }}.csr
        privatekey_path: /etc/ssl/private/{{ SERVER_FQDN }}.key
        common_name: "{{ ansible_default_ipv4.address }}"
        organization_name: "{{ ORG_NAME }}"
        subject_alt_name:
          - "DNS:{{ SERVER_FQDN }}"
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Create certificate signing request (CSR) for self-signed certificate for Fedora/CentOS
      community.crypto.openssl_csr:
        path: /etc/ssl/{{ SERVER_FQDN }}.csr
        privatekey_path: /etc/ssl/{{ SERVER_FQDN }}.key
        common_name: "{{ ansible_default_ipv4.address }}"
        organization_name: "{{ ORG_NAME }}"
        subject_alt_name:
          - "DNS:{{ SERVER_FQDN }}"
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: Create self-signed certificate from CSR for Debian/Ubuntu
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/{{ SERVER_FQDN }}.crt
        csr_path: /etc/ssl/{{ SERVER_FQDN }}.csr
        privatekey_path: /etc/ssl/private/{{ SERVER_FQDN }}.key
        entrust_not_after: +1094d
        provider: selfsigned
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Create self-signed certificate from CSR for Fedora/CentOS
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/{{ SERVER_FQDN }}.crt
        csr_path: /etc/ssl/{{ SERVER_FQDN }}.csr
        privatekey_path: /etc/ssl/{{ SERVER_FQDN }}.key
        entrust_not_after: +1094d
        provider: selfsigned
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: Enable nginx and reload now that cert is available
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        masked: no
        state: restarted
